src/Entity/Property.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;


/**
 * @ORM\Entity(repositoryClass="App\Repository\PropertyRepository")
 * @UniqueEntity("title")
 * 
 */
class Property
{
    CONST HEAT =[
        0 => 'Gaz',
        1 => 'Electrique'
    ];

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=5)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Range(min=10, max=400)
     */
    private $surface;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $bedrooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $floor;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @ORM\Column(type="integer")
     */
    private $heat;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Regex("/^[0-9]{5}$/")
     * 
     */
    private $postalCode;

    /**
     * @ORM\Column(type="boolean", options={"default": false})
     */
    private $sold;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Option", inversedBy="properties")
     */
    private $options;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updatedAt;

    /**
     * @var Picture|null
     */
    private $picture;
    
    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Picture", mappedBy="property", orphanRemoval=true, cascade={"persist"})
     */
    private $pictures;

    /**
     * @Assert\All({
     *      @Assert\Image(mimeTypes="image/jpeg")
     * })
     */
    private $pictureFiles;

    /**
     * @ORM\Column(type="float", scale=4, precision=6)
     */
    private $lat;

    /**
     * @ORM\Column(type="float", scale=4, precision=7)
     */
    private $lng;

    public function __construct()
    {
        $this->created_at = new \DateTime();
        $this->sold = false;
        $this->options = new ArrayCollection();
        $this->pictures = new ArrayCollection();
        
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return (new Slugify())->slugify($this->title);
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    public function getBedrooms(): ?int
    {
        return $this->bedrooms;
    }

    public function setBedrooms(int $bedrooms): self
    {
        $this->bedrooms = $bedrooms;

        return $this;
    }

    public function getFloor(): ?int
    {
        return $this->floor;
    }

    public function setFloor(int $floor): self
    {
        $this->floor = $floor;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getFormatedPrice(): ?string
    {
        return number_format($this->price, 0, '', ' ').' €';
    }

    public function getHeat(): ?int
    {
        return $this->heat;
    }

    public function setHeat(int $heat): self
    {
        $this->heat = $heat;

        return $this;
    }

    public function getHeatType(): ?string
    {
        return self::HEAT[$this->heat];
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postalCode;
    }

    public function setPostalCode(string $postalCode): self
    {
        $this->postalCode = $postalCode;

        return $this;
    }

    public function getSold(): ?bool
    {
        return $this->sold;
    }

    public function setSold(bool $sold): self
    {
        $this->sold = $sold;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * @return Collection|Option[]
     */
    public function getOptions(): Collection
    {
        return $this->options;
    }

    public function addOption(Option $option): self
    {
        if (!$this->options->contains($option)) {
            $this->options[] = $option;
            $option->addProperty($this);
        }

        return $this;
    }

    public function removeOption(Option $option): self
    {
        if ($this->options->contains($option)) {
            $this->options->removeElement($option);
            $option->removeProperty($this);
        }

        return $this;
    }


    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * @return Collection|Picture[]
     */
    public function getPictures(): Collection
    {
        return $this->pictures;
    }

    public function getPicture(): ?Picture
    {   
        return $this->picture;
    }

    public function setPicture(Picture $picture): self
    {   
        $this->picture = $picture;
        return $this;
    }

    public function addPicture(Picture $picture): self
    {
        if (!$this->pictures->contains($picture)) {
            $this->pictures[] = $picture;
            $picture->setProperty($this);
        }

        return $this;
    }

    public function removePicture(Picture $picture): self
    {
        if ($this->pictures->contains($picture)) {
            $this->pictures->removeElement($picture);
            // set the owning side to null (unless already changed)
            if ($picture->getProperty() === $this) {
                $picture->setProperty(null);
            }
        }

        return $this;
    }

    /**
     * @return mixed
     */ 
    public function getPictureFiles()
    {
        return $this->pictureFiles;
    }

    /**
     * @param mixed $pictureFiles
     *
     */ 
    public function setPictureFiles($pictureFiles): self
    {
        foreach ($pictureFiles as $pictureFile) {
            $picture = new Picture();
            $picture->setImageFile($pictureFile);
            $this->addPicture($picture);
        }
        $this->pictureFiles = $pictureFiles;

        return $this;
    }

    public function getLat(): ?float
    {
        return $this->lat;
    }

    public function setLat(float $lat): self
    {
        $this->lat = $lat;

        return $this;
    }

    public function getLng(): ?float
    {
        return $this->lng;
    }

    public function setLng(float $lng): self
    {
        $this->lng = $lng;

        return $this;
    }
}

src/Form/PropertyType.php
<?php

namespace App\Form;

use App\Entity\Option;
use App\Entity\Property;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PropertyType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('description')
            ->add('surface')
            ->add('rooms')
            ->add('bedrooms')
            ->add('floor')
            ->add('price')
            ->add('heat', ChoiceType::class, [
                'choices' => $this->getChoices()
            ])
            ->add('options', EntityType::class, [
                'class' => Option::class,
                'choice_label' => 'name',
                'multiple' => true
            ])
            ->add('pictureFiles', FileType::class, [
                'required' => false,
                'multiple' =>true,
                'label' => 'images'
            ])
            ->add('city')
            ->add('address')
            ->add('postalCode')
            ->add('lat', HiddenType::class)
            ->add('lng', HiddenType::class)
            ->add('sold')

        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Property::class,
            'translation_domain' => 'forms'
        ]);
    }

    private function getChoices()
    {
        $choices = Property::HEAT;
        $output = [];
        foreach ($choices as $key => $value) {
            $output[$value] = $key;
        }
        return $output;
    }
}

src/Controller/PropertyController.php
<?php

namespace App\Controller;

use App\Entity\Contact;
use App\Entity\Property;
use App\Entity\PropertySearch;
use App\Form\ContactType;
use App\Form\PropertySearchType;
use App\Notification\ContactNotification;
use App\Repository\PropertyRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class PropertyController extends AbstractController
{
    private $repository;


    public function __construct(PropertyRepository $repository)
    {
        $this->repository = $repository;
  
    }


    /**
     * @Route("/properties", name="properties")
     * @return Response 
     */
    public function index(Request $request): Response
    {
        /**
         * declaration de l'entitiée search pour le filtre de recherche
         */
        $search = new PropertySearch();
        /** formulaire de filtre */
        $form = $this->createForm(PropertySearchType::class, $search);
        $form->handleRequest($request);
        /** FIn filtre de recherche */
        /**envoi de la recherche dans le Query */
        
        /*$propertiesQuery = $this->repository->findAllVisible($search);
        /*$properties = $paginatorInterface->paginate($propertiesQuery,
                                                    $request->query->getInt('page', 1), 15 );
                                                    */
                                                   
        return $this->render('properties/index.html.twig',
                                ['current_menu'=>'active',
                                'properties' => $this->repository->paginateAllVisible($search, $request->query->getInt('page', 1) ),
                                'form'=> $form->createView()]);
    }

    /**
     * @Route("/property/{slug}/{id}", name="property.show")
     */
    public function show(Property $property, String $slug, Request $request, ContactNotification $contactNotification): Response
    {
       
         if ($property->getSlug() !== $slug) {
            return $this->redirectToRoute('property.show',[
                'id'=> $property->getId(),
                'slug' => $property->getSlug()
            ], 301);
        }

        $contact = new Contact();
        $contact->setProperty($property);
        $form = $this->createForm(ContactType::class, $contact);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            $contactNotification->notify($contact);
            $this->addFlash('success', 'Message bien envoyer');
            return $this->redirectToRoute('property.show',[
                'id'=> $property->getId(),
                'slug' => $property->getSlug()
            ]);
        }

        return $this->render('properties/show.html.twig',
        ['current_menu'=>'active',
         'property'=> $property,
         'form' => $form->createView()
        ]);
    }

}

templates/properties/_property.html.twig
<div class="card mb-4">

{% if property.picture %}

     <img src={{ vich_uploader_asset(property.picture, 'imageFile') }}  class="d-block w-100" />
      
{% else %}
    <img src={{ asset('/images/default/defaultAnnonce.jpg') }} class="card-img-top img-fluid img-thumbnail" />

{% endif %}
    
    <div class="card-body">
        <h5 class="card-title">
            <a href= {{ path('property.show', {id:property.id, slug:property.slug}) }} >{{ property.title }}</a>
        </h5>
        <p class="card-text">{{ property.description | nl2br }}</p>
        <p class="card-text">{{ property.city }} ({{ property.postalCode }})</p>
        <div class="text-primary" style="font-size:2rem; font-weight: bold;">
            {{ property.formatedPrice }}
        </div>
    </div>
</div> 

templates/properties/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}

{# module de filtre #}
    <div class="jumbotron">
        <div class="container">
            {{ form_start(form) }}
                <div class="form-row">
                    <div class="col">
                        {{ form_row(form.maxPrice) }}
                    </div>
                    <div class="col">
                        {{ form_row(form.minSurface) }}
                    </div>
                    <div class="col">
                        {{ form_row(form.options)}}
                    </div>
                    <div class="col">
                        {{ form_row(form.address, {'id': 'search_address'}) }}
                    </div>
                    <div class="col">
                        {{ form_row(form.distance) }}
                    </div>
                    <div class="col">
                        <button class="btn btn-secondary">rechercher</button>
                    </div>
                </div>
            {{ form_end(form) }}
        </div>
    </div>

{# fin module de filtre #}

    <div class="container mt-4">
        <h1> Nos biens </h1>
        {# affiche un messge si on utiulise le module de filtre #}
        {% if (form.vars.value.maxPrice or form.vars.value.minSurface) != null  %}
        <div>
            <p>Nous avons {{ properties.getTotalItemCount }} bien correspondant à votre recherche.</p>
        </div>
        {% endif %}
        {# list tout les biens #}
        <div class="row">
            {% for property in properties %}
            <div class="col-md-4">
                    <div class="card-footer text-muted d-flex justify-content-between">
                        <div class="m-0">
                            {{ property.createdAt | format_datetime('short', 'none', locale='fr') }}  
                        </div>     
                        <div class="m-0">
                            {{ property.createdAt | format_datetime('none', 'short', locale='fr') }}
                        </div>
                    </div>
                    {% include "properties/_property.html.twig" %}
                    <p>
                    
                    </p>
                  
            </div>
            {% endfor %}
                <div class="navigation mx-auto">
                    {{ knp_pagination_render(properties) }}
                </div>
        </div>
    </div>
    
{% endblock %}

{% block javascripts %}  
    <script src="https://cdn.jsdelivr.net/npm/places.js@1.18.1"></script>
    <script src="{{ asset('js/modules/address.js') }}"> </script> 
{% endblock %}

{#3956 * 2 *ASIN(SQRT(POWER(SIN(('.origin_lat.' - 'dest_lat') * pi()/180/2),2)+
COS('origin.lat' * pi()/180) * COS('dest_lat' * pi()/180) *
POWER(SIN(('.origin_lng.' - 'dest_lng') * pi()/180/2),2)
)) as distance #}

templates/properties/show.html.twig
{% extends "base.html.twig" %}

{% block title %}{{ property.title }}{% endblock %}
{% block stylesheets %}
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.6.0/dist/leaflet.css" />

{% endblock %}

{% block body %}
    <style>
  img{
  width: auto;
  height: 200vh;
  max-height: 350px;
  background: no-repeat center center scroll;
  background-position: 50%;
  -webkit-background-size: cover;
  -moz-background-size: cover;
  -o-background-size: cover;
  background-size: cover;
}
</style>
    <div class="jumbotron">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                        <ol class="carousel-indicators">
                            {% if property.pictures is not empty %}
                                {% for picture in property.pictures %}
                                <li data-target="#carouselExampleIndicators" data-slide-to="{{ loop.index - 1}}" class="{% if loop.index == 0 %} active {% endif %}"></li>
                                {% endfor %}
                            {% else %}
                                <li data-target="#carouselExampleIndicators" data-slide-to="1" class="active"></li>
                            {% endif %}
                        </ol>
                        {% if property.pictures is not empty %}
                        <div class="carousel-inner">
                            {% for  picture in property.pictures %}
                                <div class="carousel-item {% if loop.index == 1 %} active {% endif %}">
                                    <img src={{ vich_uploader_asset(picture, 'imageFile') }}  class="d-block w-100" />
                                </div>    
                            {% endfor %}
                        </div>
                        {% else %}
                        <div class="carousel-inner">
                            <div class="carousel-item active">
                                <img src={{ asset('/images/default/defaultAnnonce.jpg') }} class="d-block w-100"/>
                            </div>
                        </div>
                        {% endif %}
                        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                        </a>
                        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                        </a>
                    </div>
                </div>
                <div class="col-md-4">
                    <h1>{{ property.title}}</h1>
                    <h2>{{ property.rooms}} piéces - {{ property.surface }} m²</h2>
                    <div class="text-primary" style="font-weight:bold;font-size:4rem"> {{ property.formatedPrice }} </div>
                    <a href="#" class="btn btn-primary" id="contactButton"  {% if form.vars.submitted %} style="display: none;"{% endif %}>Contacter l'agence</a>
                    <div id="contactForm" class="mt-4" {% if not form.vars.submitted %} style="display: none;"{% endif %}>
                        {{ form_start(form) }}
                            <div class="row">
                                <div class="col">{{ form_row(form.firstname) }}</div>
                                <div class="col">{{ form_row(form.lastname) }}</div>
                            </div>
                            <div class="row">
                                <div class="col">{{ form_row(form.phone) }}</div>
                                <div class="col">{{ form_row(form.email) }}</div>
                            </div>
                        {{ form_rest(form) }}
                            <div class="form-group">
                            <button class="btn btn-primary">Envoyer</div>
                            </div>
                        {{ form_end(form) }}
                        {% if is_granted('ROLE_ADMIN') %} 
                        <div class="mt-2">
                            <a href="{{ path('admin.property.edit', {id: property.id}) }}" class="btn btn-secondary">Edit</a>
                            <form method="post" action="{{ path('admin.property.delete', {id: property.id}) }}" style="display:inline-block" onsubmit="return confirm('Etes-vous sûr de SUPPRIMER -> {{ property.title }}?')"> 
                                <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ property.id) }}">                                
                                <input type="hidden" name="_method" value="DELETE">
                                <button class="btn btn-danger">Supprimer</button>
                            </form>
                        <div>
                        {% endif %}
                    </div>  
                </div>
            </div>
        </div>
    </div>
    <div class="container mt-4">
        <p>
            {{ property.description | nl2br }}
        </p>
        <div class="row">
            <div class="col-md-8">
                <h2>Caractéristique</h2>
                <table class="table table-striped">
                    <tr>
                        <td>Surface habitable</td>
                        <td>{{ property.surface }} m²</td>
                    </tr>
                    <tr>
                        <td>Piéces</td>
                        <td>{{ property.rooms }}</td>
                    </tr>
                    <tr>
                        <td>Chambres</td>
                        <td>{{ property.bedrooms }}</td>
                    </tr>
                    <tr>
                        <td>Etages</td>
                        <td>{{ property.floor }}</td>
                    </tr>
                    <tr>
                        <td>Chauffage</td>
                        <td>{{ property.heatType }}</td>
                    </tr>
                </table>
            </div>
            <div class="col-md-4 mb-4">
                <h2>Spécificités</h2>
                <ul class="list-group">
                {% for option in property.options %}
                  <li class="list-group-item"> {{option.name}} </li>
                {% endfor %}
                </ul>
            </div>
        </div>
        <div id="map" style="width: 100%; height: 400px" data-lat="{{ property.lat }}" data-lng="{{ property.lng }}">
        </div>
    </div>
{% endblock %}
{% block javascripts %} 
        <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
        <script src="https://unpkg.com/leaflet@1.6.0/dist/leaflet.js"></script>
        <script src="{{ asset('js/modules/map.js') }}"></script>
{% endblock %}